### ISSUE TITLE
animation5.html에 대한 issue입니다.

### ISSUE THREAD

**Issue by HKCHO** [kimhaegyeong/animation#1]
취업 안녕하십니까?ㅋ

jQuery를 적용한 소스를 보고 싶습니다~

**Comment by kimhaegyeong** [comment]
아직 취업하지않았습니다!! 하하하하ㅠㅡㅠ
animation01은 나중에 width, height, color 입력받아서 동적으로 만드는 부분까지 할 예정이지만
이번주는 취업과제해야되서 다음주쯤에 다시  할  수 있지 않을까 싶어ㅠ
계속 커밋할테니까 구경와줘요ㅋㅋ
그리고 네가하고 있는 캠핑족 프로젝트 기대하고 있으니까 커밋해줘영^_^

**Comment by HKCHO** [comment]
으앙 겁나 빠르고 친절한 설명에 매우 감사~
너가 나보다 빨리 취직할 것 같네! 
같이 좋은곳 취직해서 고오급 니뽄식 선술집에서 정장입고 만나욥!
